# config/app.yml for rails-settings-cached
defaults: &defaults
  foo: "Foo"
  bar: 123
  devise_secret_key: abc123
  company:
    name: My Company
    short: Comp
    address: |
      234 Gingerway
      Guerneville
    tax_info: |
      Tax-No.: 12345
      XXXXX
      Other tax number: 4321
    phone: "0555-555555"
    fax: "0555-5555556"
    email: info@my-company.com
    legal_info: Whatever permits you
    ceo: John Doe
    bank_info: |
      Bank: Money Pot
      Account: 873456
      IBAN: 99999999999999999
      BIC: KSJNFHSDJD

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
