# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 8a486dbd0c78ec3788d8d6d623df69ecc3bb7aa2d8c3b5c55266f4b86f364e31c2aad8de705204f24389c27c47d98736833b26b9114159517a0fd05765426450

test:
  domain_name: example.com 
  secret_key_base: 887eb05cf447d63ff378ca7a8fcc843c10fd4f9f376610734b8372afdef5103d19c07231f5aed2fa859f943919bdffdd929c49be00c5ee6ed80c411da323dfda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= Setting.secret_key_base %>
